### PR TITLE
Add virtual subtypes for all remaining devices

### LINKED ISSUE #718: Добавить подтип виртуального устройства для всех устройств, которые ещё не имеют такого подтипа
Сделать, чтоб можно было в допсвойствах устройств аппаратов, агрегатов можно было привязывать сигналы: для дискретных устройств- привязка DI, для аналоговых устройств - AI

### PR DESCRIPTION
**Pull request by dimabeel**
Fixes #718

For all devices except Y, DEV_VTUG and C (PID's)

- [x] Unit-tests for functionality
- [x] Functionality
- [x] Refactoring
- [x] Manual testing
- [x] Documentation
- [x] Wait for adding this functionality in PLC program

### CODE REVIEW

**Comment by dimabeel** [comment]
There are lots of changes because during work I'm refactoring the code

**Comment by dimabeel** [comment]
Main bunch of changes located in unit-tests. You don't need to check them, because they are all passing successfully

**Comment by dimabeel** [comment]
Found a possibility to use properties, runtime parameters, tags lists in devices, not only in unit-tests. Working on apply this solution in our case.

**Comment by dimabeel** [comment]
Enough making changes. We can improve and refactor code always. Now, we have done our goal and we can test it and write documentation.

**Review by idzm — APPROVED** [review]

**Pull request merged**
